import { NavbarWrapper } from "@/components/layout/Navbar";
import "./globals.css";
import type { Metadata } from "next";
import { Poppins } from "next/font/google";


const poppins = Poppins({
  variable: "--font-poppins",
  subsets: ["latin"],
  weight: ["400", "500", "600", "700"],
  display: "swap"
});

export const metadata: Metadata = {
  title: "Movie Zone",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html
      lang="en"
      className={`${poppins.variable} antialiased`}
    >
      <body className=" bg-grey-100 text-grey-1000 h-full">
        <NavbarWrapper />
        {children}
      </body>
    </html>
  );
}
